import { UserProfile, Homework, Grade, Reward, RewardRedemption } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'teacher-1',
    name: 'Prof. Alexandre Martin',
    email: 'alexandre.martin@parkours.fr',
    role: 'teacher',
    avatar: '👨‍🏫',
    points: 0,
    totalXp: 0,
    level: 10,
    streak: 0,
    badges: ['Enseignant Référent', 'Tuteur Parkours'],
    classGroup: 'Tuteur / Professeur',
  },
  // UNIQUEMENT LES 5 ÉLÈVES DE 5ÈME DEMANDÉS
  {
    id: 'student-come',
    name: 'Côme Cordoba',
    email: 'come.cordoba@eleve.fr',
    role: 'student',
    avatar: '🧑‍🎓',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-adrien',
    name: 'Adrien Thirry',
    email: 'adrien.thirry@eleve.fr',
    role: 'student',
    avatar: '👨‍💻',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-gustave',
    name: 'Gustave Auger',
    email: 'gustave.auger@eleve.fr',
    role: 'student',
    avatar: '🚀',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-barthelemy',
    name: 'Barthelemy Pinaud',
    email: 'barthelemy.pinaud@eleve.fr',
    role: 'student',
    avatar: '📚',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-maxime',
    name: 'Maxime Dornbusch',
    email: 'maxime.dornbusch@eleve.fr',
    role: 'student',
    avatar: '🔬',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
];

export const INITIAL_HOMEWORK: Homework[] = [
  {
    id: 'hw-1',
    title: 'Fiche d\'exercices : Fractions & Calcul mental',
    subject: 'Mathématiques',
    description: 'Effectuer les 5 exercices de simplification de fractions et problèmes de partage.',
    dueDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    xpReward: 50,
    assignedTo: ['all'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    submissions: {
      'student-come': { status: 'todo' },
      'student-adrien': { status: 'todo' },
      'student-gustave': { status: 'todo' },
      'student-barthelemy': { status: 'todo' },
      'student-maxime': { status: 'todo' },
    },
  },
  {
    id: 'hw-2',
    title: 'Compte-rendu TP : Les états de la matière & la masse volumique',
    subject: 'Physique-Chimie',
    description: 'Schématiser l\'expérience de distillation et répondre aux 3 questions de bilan.',
    dueDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
    xpReward: 60,
    assignedTo: ['all'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    submissions: {
      'student-come': { status: 'todo' },
      'student-adrien': { status: 'todo' },
      'student-gustave': { status: 'todo' },
      'student-barthelemy': { status: 'todo' },
      'student-maxime': { status: 'todo' },
    },
  },
  {
    id: 'hw-3',
    title: 'Analyse de texte : Fables de La Fontaine (5ème)',
    subject: 'Français',
    description: 'Rédiger un résumé en 8 lignes et dégager la morale de la fable étudiée.',
    dueDate: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
    xpReward: 45,
    assignedTo: ['all'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    submissions: {
      'student-come': { status: 'todo' },
      'student-adrien': { status: 'todo' },
      'student-gustave': { status: 'todo' },
      'student-barthelemy': { status: 'todo' },
      'student-maxime': { status: 'todo' },
    },
  },
];

export const INITIAL_GRADES: Grade[] = [];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    title: '🎮 30 min Pause Jeux Vidéo / Détente',
    description: 'Une pause détente sans devoirs pendant la séance de tutorat.',
    cost: 100,
    icon: '🎮',
    category: 'Privilèges',
    stock: 10,
  },
  {
    id: 'rew-2',
    title: '🃏 Joker Retard Devoir (+24h)',
    description: 'Permet de rendre un devoir maison avec 24h de délai en plus.',
    cost: 150,
    icon: '🃏',
    category: 'Bonus',
    stock: 5,
  },
  {
    id: 'rew-3',
    title: '🎯 Choix du Sujet du Prochain Atelier',
    description: 'Tu choisis le thème ou la matière du prochain exercice !',
    cost: 200,
    icon: '🎯',
    category: 'Privilèges',
    stock: 3,
  },
  {
    id: 'rew-4',
    title: '🎁 Carte Cadeau Fnac / Amazon 10€',
    description: 'Un bon d\'achat offert pour te récompenser de tes efforts.',
    cost: 500,
    icon: '🎁',
    category: 'Cadeaux',
    stock: 2,
  },
  {
    id: 'rew-5',
    title: '🍕 Session Tutorat Pizza & Boissons',
    description: 'Une séance festive avec pizzas pour célébrer vos progrès !',
    cost: 400,
    icon: '🍕',
    category: 'Activités',
    stock: 4,
  },
];

export const INITIAL_REDEMPTIONS: RewardRedemption[] = [];
