import { UserProfile, Homework, Grade, Reward, RewardRedemption } from './types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'teacher-1',
    name: 'Amaury Despretz',
    email: 'amaury.despretz@parkours.fr',
    role: 'teacher',
    avatar: '👨‍🏫',
    points: 0,
    totalXp: 0,
    level: 10,
    streak: 0,
    badges: ['Enseignant Référent', 'Tuteur Parkours'],
    classGroup: 'Tuteur',
  },
  // UNIQUEMENT LES 5 ÉLÈVES DE 5ÈME DEMANDÉS
  {
    id: 'student-come',
    name: 'Côme Cordoba',
    email: 'come.cordoba@eleve.fr',
    role: 'student',
    avatar: '🧑‍🎓',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-adrien',
    name: 'Adrien Thirry',
    email: 'adrien.thirry@eleve.fr',
    role: 'student',
    avatar: '👨‍💻',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-gustave',
    name: 'Gustave Auger',
    email: 'gustave.auger@eleve.fr',
    role: 'student',
    avatar: '🚀',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-barthelemy',
    name: 'Barthelemy Pinaud',
    email: 'barthelemy.pinaud@eleve.fr',
    role: 'student',
    avatar: '📚',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
  {
    id: 'student-maxime',
    name: 'Maxime Dornbusch',
    email: 'maxime.dornbusch@eleve.fr',
    role: 'student',
    avatar: '🔬',
    points: 0,
    totalXp: 0,
    level: 1,
    streak: 0,
    badges: ['🌱 Élève 5ème'],
    classGroup: '5ème',
  },
];

export const INITIAL_HOMEWORK: Homework[] = [];

export const INITIAL_GRADES: Grade[] = [];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    title: '🎮 30 min Pause Jeux Vidéo / Détente',
    description: 'Une pause détente sans devoirs pendant la séance de tutorat.',
    cost: 100,
    icon: '🎮',
    category: 'Privilèges',
    stock: 10,
  },
  {
    id: 'rew-2',
    title: '🃏 Joker Retard Devoir (+24h)',
    description: 'Permet de rendre un devoir maison avec 24h de délai en plus.',
    cost: 150,
    icon: '🃏',
    category: 'Bonus',
    stock: 5,
  },
  {
    id: 'rew-3',
    title: '🎯 Choix du Sujet du Prochain Atelier',
    description: 'Tu choisis le thème ou la matière du prochain exercice !',
    cost: 200,
    icon: '🎯',
    category: 'Privilèges',
    stock: 3,
  },
  {
    id: 'rew-4',
    title: '🎁 Carte Cadeau Fnac / Amazon 10€',
    description: 'Un bon d\'achat offert pour te récompenser de tes efforts.',
    cost: 500,
    icon: '🎁',
    category: 'Cadeaux',
    stock: 2,
  },
  {
    id: 'rew-5',
    title: '🍕 Session Tutorat Pizza & Boissons',
    description: 'Une séance festive avec pizzas pour célébrer vos progrès !',
    cost: 400,
    icon: '🍕',
    category: 'Activités',
    stock: 4,
  },
];

export const INITIAL_REDEMPTIONS: RewardRedemption[] = [];
